(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d,f="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},g;if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var h;a:{var k={V:!0},l={};try{l.__proto__=k;h=l.V;break a}catch(a){}h=!1}g=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var m=g,n=function(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},p=n(this);var u=function(a,b){var c=void 0===c?null:c;var e=document.createEvent("CustomEvent");e.initCustomEvent(a,!0,!0,c);b.dispatchEvent(e)};var w=function(a){if(!a.gwdIsLoaded()){var b=v(a);b?b.gwdIsLoaded()&&a.gwdLoad():a.gwdLoad()}},x=function(a){if(!a.gwdIsActive()){var b=v(a);b?b.gwdIsActive()&&a.gwdActivate():a.gwdActivate()}},y=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},v=function(a){if(y(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&y(a))return a;return null};var z=function(a){return Math.min(Math.max(a,1),Infinity)};var A=function(){this.S=""};A.prototype.toString=function(){return"SafeScript{"+this.S+"}"};A.prototype.i=function(a){this.S=a};(new A).i("");var B=function(){this.U=""};B.prototype.toString=function(){return"SafeStyle{"+this.U+"}"};B.prototype.i=function(a){this.U=a};(new B).i("");var C=function(){this.T=""};C.prototype.toString=function(){return"SafeStyleSheet{"+this.T+"}"};C.prototype.i=function(a){this.T=a};(new C).i("");var D=function(){this.R=""};D.prototype.toString=function(){return"SafeHtml{"+this.R+"}"};D.prototype.i=function(a){this.R=a};(new D).i("<!DOCTYPE html>");(new D).i("");(new D).i("<br>");var E={Y:"alignment",Z:"autoplay",$:"clipheight",aa:"clipwidth",ba:"duration",ca:"endonstartframe",da:"imagesource",ea:"loopcount",fa:"offsetx",ga:"offsety",ha:"quickready",ia:"reverseplay",ja:"scaling",ka:"totalframecount"},F=[],G=0,H;for(H in E)F[G++]=E[H];
var I=function(){var a=HTMLElement.call(this)||this;a.W="gwd_spritesheet_"+(2147483648*Math.random()|0);a.a=null;a.B=!1;a.J=!1;a.l=null;a.O=0;a.N=0;a.H="";a.C=0;a.K=0;a.c=64;a.g=64;a.I=0;a.X=0;a.m=!1;a.P=!1;a.u=!1;a.f=1;a.s=100;a.j=0;a.b=0;a.o=0;a.h=!1;a.L=0;a.A=0;a.F=0;a.D=0;a.w="auto";a.M="top left";a.G=null;a.v=!1;return a},J=HTMLElement;I.prototype=f(J.prototype);I.prototype.constructor=I;
if(m)m(I,J);else for(var K in J)if("prototype"!=K)if(Object.defineProperties){var L=Object.getOwnPropertyDescriptor(J,K);L&&Object.defineProperty(I,K,L)}else I[K]=J[K];d=I.prototype;
d.connectedCallback=function(){if(!this.v){for(;this.firstChild;)this.removeChild(this.firstChild);this.a=this.ownerDocument.createElement("canvas");this.a.className=this.W;this.appendChild(this.a);this.O=parseInt(window.getComputedStyle(this,null).getPropertyValue("width"),10);this.N=parseInt(window.getComputedStyle(this,null).getPropertyValue("height"),10);this.m=this.hasAttribute("autoplay");this.P=this.hasAttribute("endonstartframe");this.u=this.hasAttribute("reverseplay");this.G=this.a.getContext("2d");
this.v=!0;M(this);N(this)}w(this)};
d.attributeChangedCallback=function(a,b,c){switch(a){case "imagesource":this.v&&this.pause();this.H=c||"";this.v&&(this.B=!1,w(this));break;case "offsetx":this.C=parseInt(c,10);break;case "offsety":this.K=parseInt(c,10);break;case "clipwidth":this.c=z(parseInt(c,10));M(this);break;case "clipheight":this.g=z(parseInt(c,10));M(this);break;case "scaling":c?(this.w=c,M(this)):this.setAttribute(a,"auto");break;case "alignment":c?(this.M=c,N(this)):this.setAttribute(a,"top left");break;case "totalframecount":this.f=
z(parseInt(c,10));break;case "duration":this.s=z(parseInt(c,10));break;case "loopcount":this.j=parseInt(c,10);break;case "autoplay":(this.m="true"==c)?this.play():this.pause()}};d.gwdLoad=function(){/^[\s\xa0]*$/.test(this.H)?(this.B=!0,u("ready",this),x(this)):(O(this),this.hasAttribute("quickready")&&u("ready",this))};d.gwdIsLoaded=function(){return this.B};d.gwdActivate=function(){this.m?this.gwdIsLoaded()&&this.play():this.gwdIsLoaded()&&P(this,0);this.J=!0};
d.gwdDeactivate=function(){this.pause();this.J=!1};d.gwdIsActive=function(){return this.J};
var P=function(a,b){if(a.l){var c=z(Math.floor((a.I-a.C)/a.c)),e=z(Math.floor(a.I/a.c)),q=a.C,r=a.K,t=b;b>=c&&(t=(b-c)%e,q=0,r+=a.g*Math.floor(1+(b-c)/e));a.G.clearRect(0,0,a.c,a.g);a.G.drawImage(a.l,q+t*a.c,r,a.c,a.g,0,0,a.c,a.g)}},M=function(a){if(a.v){var b=a.O/a.c,c=a.N/a.g;"100% 100%"==a.w?(a.a.style.width="100%",a.a.style.height="100%",a.style.overflow="visible"):"contain"==a.w?(b=b<c?b:c,a.a.style.width=a.c*b+"px",a.a.style.height=a.g*b+"px",a.style.overflow="visible"):("cover"==a.w?(b=b<c?
c:b,a.a.style.width=a.c*b+"px",a.a.style.height=a.g*b+"px"):(a.a.style.width=a.c+"px",a.a.style.height=a.g+"px"),a.style.overflow="hidden");a.a.width=a.c;a.a.height=a.g}},N=function(a){if(a.v&&"100% 100%"!=a.w){var b=parseInt(a.a.style.width,10),c=parseInt(a.a.style.height,10);a.style.position="absolute;";a.a.style.position="relative";switch(a.M){case "center":a.a.style.left="50%";a.a.style.top="50%";a.a.style.transform="translate(-"+b/2+"px, -"+c/2+"px)";break;case "bottom":a.a.style.left="50%";
a.a.style.top="100%";a.a.style.transform="translate(-"+b/2+"px, -"+c+"px)";break;case "bottom left":a.a.style.left="0%";a.a.style.top="100%";a.a.style.transform="translate(0px, -"+c+"px)";break;case "bottom right":a.a.style.left="100%";a.a.style.top="100%";a.a.style.transform="translate(-"+b+"px, -"+c+"px)";break;case "left":a.a.style.left="0%";a.a.style.top="50%";a.a.style.transform="translate(0px, -"+c/2+"px)";break;case "right":a.a.style.left="100%";a.a.style.top="50%";a.a.style.transform="translate(-"+
b+"px, -"+c/2+"px)";break;case "top":a.a.style.left="50%";a.a.style.top="0%";a.a.style.transform="translate(-"+b/2+"px, 0px)";break;case "top left":a.a.style.top="0%";a.a.style.left="0%";a.a.style.transform="translate(0px, 0px)";break;case "top right":a.a.style.top="0%",a.a.style.left="100%",a.a.style.transform="translate(-"+b+"px, 0px)"}}},Q=function(a){a.h&&(P(a,a.b),a.u?(a.b=(a.b-1+a.f)%a.f,a.b==a.f-1&&a.o++):(a.b==a.f-1&&a.o++,a.b=(a.b+1)%a.f),a.j=parseInt(a.j,10),a.o<a.j||0==a.j?(a.A+=a.s,a.F=
(new Date).getTime()-a.L-a.A,a.D=setTimeout(function(){Q(a)},a.s-a.F)):a.D=1==a.P?setTimeout(function(){a.u?a.goToFrame(a.f-1):a.goToFrame(0);u("animationend",a)},a.s):setTimeout(function(){a.h=!1;u("animationend",a)},a.s))},R=function(a){a.L=+new Date;a.A=-a.s;a.F=0;clearTimeout(a.D)},O=function(a){a.l=new Image;a.l.addEventListener("load",function(){a.I=parseInt(a.l.naturalWidth,10);a.X=parseInt(a.l.naturalHeight,10);R(a);a.u&&(a.b=a.f-1);P(a,a.b);1==a.m&&(a.h=!0,Q(a));a.B=!0;u("ready",a);x(a)});
a.l.src=a.H};d=I.prototype;d.getImage=function(){return this.l};d.getCurrentFrame=function(){return this.b};d.newAnimation=function(a,b,c,e,q,r,t,S,T){this.C=parseInt(a,10);this.K=parseInt(b,10);this.u=T;this.m=S;this.f=parseInt(q,10);this.s=parseInt(r,10);this.j=parseInt(t,10);this.o=this.b=0;a=z(parseInt(c,10));e=z(parseInt(e,10));if(a!=this.c||e!=this.g)this.c=a,this.g=e,M(this);1==this.u&&(this.b=this.f-1);this.o=0;1==this.m?this.restart():(this.h=!1,P(this,0))};
d.goToFrame=function(a){0>a&&(a=this.f-Math.abs(a)%this.f);this.b=a%this.f;P(this,this.b);this.h=!1};d.play=function(){(this.o<this.j||0==this.j)&&0==this.h&&(u("animationplay",this),this.h=!0,R(this),Q(this))};d.pause=function(){this.h&&(u("animationpause",this),this.h=!1)};d.togglePlay=function(){0==this.h?this.play():this.pause()};d.restart=function(){u("animationrestart",this);this.b=0;this.u&&(this.b=this.f-1);this.o=0;0==this.h&&this.play()};d.previousFrame=function(){this.b--;this.goToFrame(this.b)};
d.nextFrame=function(){this.b++;this.goToFrame(this.b)};p.Object.defineProperties(I,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return F}}});customElements.define("gwd-spritesheet",I);}).call(this);
